flaskapp/main/routes.py
from flaskapp import db
from flaskapp.main.forms import MessageForm
from flask import render_template, url_for, flash, redirect, Blueprint
from flaskapp.main.utils import arabic_to_roman
from flaskapp.main.models import Message
from datetime import datetime

date = datetime.today()
year = arabic_to_roman(int(date.year))

main = Blueprint('main', __name__)


@main.route("/", methods=['GET', 'POST'])
@main.route("/home", methods=['GET', 'POST'])
@main.route("/index", methods=['GET', 'POST'])
def index():
    image_file = url_for('static', filename='img/profile_pics/space.jpg')
    form = MessageForm()
    if form.validate_on_submit():
        message = Message(name=form.name.data, email=form.email.data, phone=form.phone.data, body=form.body.data)
        db.session.add(message)
        db.session.commit()
        flash('Your message has been sent.', 'success')
        return redirect(url_for('main.index'))
    return render_template('index.html', title='Home', form=form, year=year, image_file=image_file)

# Add unique route? or simply link html
@main.route("/underconstruction")
def construction():
    return render_template('errors/underconstruction.html', title='Policy')


@main.route("/termsofuse")
def terms():
    return render_template('terms.html', title='Website Terms of Use', page="tof")


@main.route("/privacypolicy")
def privacy():
    return render_template('privacy.html', title='Website PRIVACY POLICY', page="pp")

flaskapp/templates/general-layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags-->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>SUSS.SPACE</title>

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <!-- Bootstrap core CSS -->
  <link href="static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="static/css/general-layout.min.css" rel="stylesheet">

</head>

<body id="page-top">

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="#page-top">SUSS.SPACE</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav text-uppercase ml-auto">
          {% if page == "pp"%}
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{{ url_for('main.terms') }}">Terms of Use</a>
          </li>
          {% elif page == "tof" %}
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{{ url_for('main.privacy') }}">Privacy Policy</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <section class="no" style="padding: 106px 0 0 0;">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
      </div>
    </div>
  </section>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <span class="copyright">Copyright &copy; SUSS.SPACE</span>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="static/vendor/jquery/jquery.min.js"></script>
  <script src="static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Plugin JavaScript -->
  <script src="static/vendor/jquery-easing/jquery.easing.min.js"></script>

  <!-- Custom scripts for this template -->
  <script src="static/js/agency.min.js"></script>

</body>

</html>

flaskapp/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags-->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>SUSS.SPACE</title>

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <!-- Bootstrap core CSS -->
  <link href="static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="static/css/index.min.css" rel="stylesheet">

</head>

<body id="page-top">

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="#page-top">SUSS.SPACE - {{ year }}</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav text-uppercase ml-auto">
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#contact">CONTACT</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Header -->
  <header class="masthead">
    <div class="container">
      <div class="intro-text">
        <div class="intro-heading text-uppercase">
        <br></br>
        <br></br>
        </div>
      </div>
    </div>
  </header>

  <!-- Contact -->
  <section id="contact">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <h2 class="section-heading text-uppercase">Contact Me</h2>
        </div>
      </div>
      {% with message = get_flashed_messages(with_categories=true) %}
        {% if message %}
          {% for category, message in message %}
            <div class="alert alert-{{ category }}">
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}
      <div class="row">
        <div class="col-lg-12">
            <form method="POST">
                <div class="row">
                  <div class="col-md-6">
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">
                      <div class="form-group">
                          {% if form.name.errors %}
                              {{ form.name(class="form-control form-control-lg is-invalid") }}
                              <div class="invalid-feedback">
                                  {% for error in form.name.errors %}
                                      <span>{{ error }}</span>
                                  {% endfor %}
                              </div>
                          {% else %}
                              {{ form.name(class="form-control form-control-lg") }}
                          {% endif %}
                      </div>
                      <div class="form-group">
                          {% if form.email.errors %}
                              {{ form.email(class="form-control form-control-lg is-invalid") }}
                              <div class="invalid-feedback">
                                  {% for error in form.email.errors %}
                                      <span>{{ error }}</span>
                                  {% endfor %}
                              </div>
                          {% else %}
                              {{ form.email(class="form-control form-control-lg") }}
                          {% endif %}
                      </div>
                      <div class="form-group">
                          {% if form.phone.errors %}
                              {{ form.phone(class="form-control form-control-lg is-invalid") }}
                              <div class="invalid-feedback">
                                  {% for error in form.phone.errors %}
                                      <span>{{ error }}</span>
                                  {% endfor %}
                              </div>
                          {% else %}
                              {{ form.phone(class="form-control form-control-lg") }}
                          {% endif %}
                      </div>
                    </div>
                    <div class="col-md-6">
                    <div class="form-groupe">
                      {% if form.body.errors %}
                          {{ form.body(class="form-control form-control-lg is-invalid") }}
                          <div class="invalid-feedback">
                              {% for error in form.body.errors %}
                                  <span>{{ error }}</span>
                              {% endfor %}
                          </div>
                      {% else %}
                          {{ form.body(class="form-control form-control-lg") }}
                      {% endif %}
                    </div>
                    </div>
                  </fieldset>
              </div>
            </div>
            </div>
          <center>
            <div class="form-group">
            {{ form.submit(class="btn btn-primary btn-xl text-uppercase") }}
            </div>
          </center>
        </form>
        </div>
      </div>
    </div>
  </section>


  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <span class="copyright">Copyright &copy; SUSS.SPACE</span>
        </div>
        <div class="col-md-4">
          <ul class="list-inline social-buttons">
            <li class="list-inline-item">
              <a href="https://www.instagram.com/seeing.suss">
                <i class="fab fa-instagram"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="https://www.facebook.com/jacob.sussmilch">
                <i class="fab fa-facebook-f"></i>
              </a>
            </li>
          </ul>
      </div>
        <div class="col-md-4">
          <ul class="list-inline quicklinks">
            <li class="list-inline-item">
              <a href="{{ url_for('main.privacy') }}">Privacy Policy</a>
            </li>
            <li class="list-inline-item">
              <a href="{{ url_for('main.terms') }}">Terms of Use</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="static/vendor/jquery/jquery.min.js"></script>
  <script src="static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Plugin JavaScript -->
  <script src="static/vendor/jquery-easing/jquery.easing.min.js"></script>

  <!-- Custom scripts for this template -->
  <script src="static/js/agency.min.js"></script>

</body>

</html>